name: CI

on:
  push:
    branches: [ develop ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: pull, build & run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        script: |
            cd ${{ secrets.PROJECTPATH }}
            chmod +x deploy-stage.sh && ./deploy-stage.sh
            